docs(ru) guide/a11y-semantics.md translated
translation-gang/docs-next pull request #10
Opened 2021-01-20 21:36 UTC by lex111

cc @Alex-Sokolov

2021-01-21 10:52 UTC, Alex-Sokolov requested changes

2021-01-21 10:52 UTC, Alex-Sokolov commented on src/ru/guide/a11y-semantics.md
> +При создании формы используйте следующие элементы: `<form>`, `<label>`, `<input>`, `<textarea>` и `<button>`.
При создании форм можно использовать следующие элементы

2021-01-21 10:52 UTC, Alex-Sokolov commented on src/ru/guide/a11y-semantics.md
> +Как правило, метки размещаются сверху или слева от полей формы:
может так...

Обычно `<label>` с описанием размещают сверху или слева от поля формы

2021-01-21 10:52 UTC, Alex-Sokolov commented on src/ru/guide/a11y-semantics.md
> +Обратите внимание, если добавить `autocomplete='on'` к самому элементу формы, то он этот атрибут применится ко всем полям формы. Для каждого поля можно задать разные [значения в атрибуте autocomplete
Обратите внимание, можно добавить ... к самому элементу формы и этот атрибут применится ко всем полям формы. Каждому полю можно задать свои значения атрибута autocomplete

2021-01-21 10:52 UTC, Alex-Sokolov commented on src/ru/guide/a11y-semantics.md
> +В метках даётся описание полей формы; они устанавливают связь между элементами с атрибутами `for` и `id`:
Указывайте метки для описания полей формы, а также установления связи между элементами с атрибутами ...

2021-01-21 10:52 UTC, Alex-Sokolov commented on src/ru/guide/a11y-semantics.md
> +Если открыть инструменты разработки (например, DevTools в браузере Chrome) на вкладке Elements, затем перейти на вкладку Accessibility, можно заметить, что имя поле извлекается из её метки:
Если исследовать элемент с помощью инструментов разработчика (например ... ) и перейти на вкладку Accessibility внутри раздела Elements, то можно увидеть что имя поля извлекается из связанной с ним метки

2021-01-21 10:52 UTC, Alex-Sokolov commented on src/ru/guide/a11y-semantics.md
> +Возможно, вы видели, как поля ввода находится внутри элемента метки:
Я стараюсь по руководству от всяких вы\мы\ты уйти по максимуму... может тут что-то вроде

Часто можно встретить случаи, когда поле ввода находится внутри его элемента с меткой

2021-01-21 10:52 UTC, Alex-Sokolov commented on src/ru/guide/a11y-semantics.md
> +Однако так лучше не делать, поскольку вспомогательные технологии лучше работают с метками, явно связанные с идентификаторами.
Однако явное указание меткам соответствующий id лучше поддерживается вспомогательными технологиями

2021-01-21 10:52 UTC, Alex-Sokolov commented on src/ru/guide/a11y-semantics.md
> +С помощью атрибута [`aria-label`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute) можно задать описание поля для вспомогательных технол
Указывать имя поля для использования вспомогательными технологиями можно с помощью атрибута ...

2021-01-21 10:52 UTC, Alex-Sokolov commented on src/ru/guide/a11y-semantics.md
> +В Chrome DevTools посмотрите сами, что метка формы изменилась:
Можно убедиться самостоятельно что имя элемента изменилось с помощью инструментов разработчика

2021-01-21 10:52 UTC, Alex-Sokolov commented on src/ru/guide/a11y-semantics.md
> +Использование атрибута [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute) похоже на `aria-label`, за исключением
отображается - видим?

2021-01-21 10:52 UTC, Alex-Sokolov commented on src/ru/guide/a11y-semantics.md
> +Атрибут [aria-describedby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-describedby_attribute) аналогичен `aria-labelledby`, но представляет собой до
используется аналогично ... но предоставляет дополнительную информацию, которая может потребоваться пользователю. Это можно использовать например для описания ограничений ввода

2021-01-21 10:52 UTC, Alex-Sokolov commented on src/ru/guide/a11y-semantics.md
> +### Подсказка поля
вот не знаю переводить или нет... или может подсказка внутри пустого поля назвать прям так многословно?

2021-01-21 10:52 UTC, Alex-Sokolov commented on src/ru/guide/a11y-semantics.md
> +Постарайтесь не использовать подсказки полей, поскольку они могут запутать многих пользователей.
Старайтесь ограничить использования подсказок внутри полей, так как они могут запутать пользователя

2021-01-21 10:52 UTC, Alex-Sokolov commented on src/ru/guide/a11y-semantics.md
> +Добавление `aria-hidden="true"` скроет элемент от вспомогательных технологий, однако он по-прежнему будет показываться другим пользователям. Не используйте его на фокусируемых элементах, только для д
добавляйте только для декоративных, дублирующихся или не отображаемых на экране элементов ?

2021-01-21 10:53 UTC, Alex-Sokolov commented
Спасибо! Расписал несколько предложений... некоторые моменты сам не знаю как лучше, может у тебя еще идеи будут

2021-01-21 18:11 UTC, lex111 commented on src/ru/guide/a11y-semantics.md
> +### Подсказка поля
В таких случаях я прибегаю к помощи словаря https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#placeholder в зависимости от контекста можно просто упрощать до "подсказки".

2021-01-21 18:13 UTC, lex111 commented on src/ru/guide/a11y-semantics.md
> +Как правило, метки размещаются сверху или слева от полей формы:
Мне нравится больше вариант с переводом, если бы в оригинале использовали название элемента, то да, а здесь просто название этого элемента, который обычно переводится как "метка".

2021-01-21 18:14 UTC, lex111 commented
Спасибо, хотя не со всем согласен, но почти все правки внёс (потому что тебе виднее).

2021-01-22 09:51 UTC, Alex-Sokolov approved these changes

2021-01-22 09:51 UTC, merged

2021-01-22 09:52 UTC, Alex-Sokolov commented
@lex111 ты если что пиши :) подискутируем, вдруг где глаз замылился