docs(ru) guide/reactivity.md
translation-gang/docs-next pull request #14
Opened 2021-02-08 17:23 UTC by Brisstor

Как обычно, буду рад комментам и поправкам. Сам, конечно, 2 раза прочитал.
И ещё - кодпены в триальном режиме работают, не уверен, нормально это или нет. 
Также, не переводил текст в самих кодпенах. Если надо - сделаю.

2021-02-10 19:01 UTC, lex111 commented on src/ru/guide/reactivity.md
> +Это было поверхноестное объяснение и оно требует некоторых знаний о [Proxy](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Proxy) для полного понимания. Давайте немного
```suggestion
Это было поверхностное объяснение и оно требует некоторых знаний о [Proxy](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Proxy) для полного понимания. Давайте немного углубимся. Есть достаточно много литературы про Proxy, но что вам действительно важно знать, что **Прокси — это объект, который содержит в себе другой объект или функцию и позволяет "перехватить" их.**
```

2021-02-10 19:09 UTC, lex111 commented on src/ru/guide/reactivity.md
> +Пока что мы просто оборачиваем объект и возвращаем его. Круто, но ещё не так полезно. Но взгляните сюда, мы также можем перехватить этот объект во время оборачивания его в Proxy. Этот перехват называ
Лучше сохранять пустые строки, как в оригинале, чтобы легче потом было сравнивать изменения.

```suggestion

Пока что мы просто оборачиваем объект и возвращаем его. Круто, но ещё не так полезно. Но взгляните сюда, мы также можем перехватить этот объект во время оборачивания его в Proxy. Этот перехват называется ловушкой. 
```

2021-02-10 19:09 UTC, lex111 commented on src/ru/guide/reactivity.md
> +Помимо вызова console.log мы можем выполнить здесь всё, что захотим. В том числе, при желании, мы даже можем _не_ возвращать реальное значение. Это то, что делает Proxy настолько мощными для создания
То же самое - нужна пустая строка, которая есть в оригинале.

```suggestion

Помимо вызова console.log мы можем выполнить здесь всё, что захотим. В том числе, при желании, мы даже можем _не_ возвращать реальное значение. Это то, что делает Proxy настолько мощными для создания API.
```

2021-02-10 19:20 UTC, lex111 commented on src/ru/guide/reactivity.md
> +Более того, у Proxy есть ешё одна особенность. Вместо того, чтобы просто вернуть значение в виде: `target[prop]`, мы можем пойти дальше и использовать `Reflect`, который позволит нам корректно привяз
```suggestion
Более того, у Proxy есть ещё одна особенность. Вместо того, чтобы просто вернуть значение в виде `target[prop]`, можно пойти дальше и воспользоваться `Reflect`, чтобы корректно привязать `this`. Получится примерно следующее:
```

2021-02-10 19:26 UTC, lex111 commented on src/ru/guide/reactivity.md
> +Ранее мы уже упоминали, что для того, чтобы API обновляло результат когда одно из значений изменяется, нам придётся устанавливать новые значения при изменении. Давайте сделаем это в функции-обработчи
```suggestion
Как упоминалось ранее, чтобы API обновил результат при каком-либо изменении, нужно установить новые значения. Давайте сделаем это в функции-обработчике `track`, куда передадим `target` и `key`.
```

2021-02-10 19:28 UTC, lex111 commented on src/ru/guide/reactivity.md
> +У каждого экземпляра компонента есть соответствущий наблюдатель, который вносит в зависимости любые свойства, используемые в момент отрисовки. Позже, при срабатывании сеттера зависимости, он уведомит
```suggestion
У каждого экземпляра компонента есть соответствующий наблюдатель, который вносит в зависимости любые свойства, используемые в момент отрисовки. Позже, при срабатывании сеттера зависимости, он уведомит наблюдателя, что, в свою очередь, приведёт к перерисовке компонента.
```

2021-02-10 19:33 UTC, lex111 commented on src/ru/guide/reactivity.md
> +Использование Proxy вводит новую оговорку, о которой следует знать: проксируемый объект не равен оригинальному объекту при строгом сравнении (`===`). Например:
```suggestion
При использовании Proxy следует помнить о том, что проксируемый объект не равен оригинальному объекту при строгом сравнении (`===`). Например:
```

2021-02-10 19:34 UTC, lex111 commented on src/ru/guide/reactivity.md
> +Проксированный объект невидим для пользователя, но под капотом это позволяет Vue следить за изменениями и уведомлять о них при обращении или редактировании свойств объекта. Начиная с Vue 3, наша реал
```suggestion
Проксированный объект невидим для пользователя, но под капотом он позволяет Vue следить за изменениями и уведомлять о них при обращении или редактировании свойств объекта. Начиная с Vue 3, наша реализация реактивности теперь доступна как [отдельный модуль](https://github.com/vuejs/vue-next/tree/master/packages/reactivity). Оговоримся, что преобразованные объекты логируются в консоли по-разному для разных браузеров. Для более удобной работы с этими объектами вы можете установить [vue-devtools](https://github.com/vuejs/vue-devtools).
```

2021-02-11 18:33 UTC, Brisstor commented
Поправил, спасибо. Пустые строки оставляю обычно, эти 2 случайно потёр :)

2021-02-11 19:45 UTC, lex111 commented on src/ru/guide/reactivity.md
> +Помимо вызова console.log мы можем выполнить здесь всё, что захотим. В том числе, при желании, мы даже можем _не_ возвращать реальное значение. Это то, что делает Proxy настолько мощными для создания
@Brisstor отлично, спасибо, здесь я ещё изменил оригинальный перевод, чтобы он носит обезличенную форму, во всём остальном переводе избегаем использовать личные формы вроде "мы/вы" и т.д. Вы можете поправить это?

2021-02-12 11:34 UTC, lex111 approved these changes
Как по мне, всё хорошо. @Alex-Sokolov посмотри, пожалуйста.

2021-02-14 08:13 UTC, Alex-Sokolov requested changes

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +Если ввести цифру 2 в первую ячейку, 3 во вторую и попробовать получить сумму с помощью встроенной в Excel функции SUM, таблица её посчитает. Ничего необычного. Но если повторно изменить число в перв
Ничего неожиданного может?

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +// сумма
Тут вроде как имя переменной указывали в которой сумма будет, надо ли переводить?

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +Если обновить первое значение, сумма не скорректируется.
...сумма не обновится с учетом нового значения?

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +- Найти функцию, которая их изменяет
Может отслеживать функцию тоже?

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +Когда простой JavaScript-объект передаётся в приложение или экземпляр Vue в качестве опции `data`, Vue обходит все его свойства и превращает их в [Proxy](https://developer.mozilla.org/ru/docs/Web/Jav
Обе версии предоставляют одинаковое API, но ...

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +Это было поверхностное объяснение и оно требует некоторых знаний о [Proxy](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Proxy) для полного понимания. Давайте немного
тут тоже либо тире убрать, либо это убрать

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +Помимо вывода в консоль можно сделать всё что угодно. Кроме этого, при желании можно даже _не_ возвращать значение. Вот поэтому Proxy настолько эффективен для создания API.
"не возвращать" для заметности лучше в курсив сделать

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +Более того, у Proxy есть ещё одна особенность. Вместо того, чтобы просто вернуть значение в виде: `target[prop]`, можно пойти дальше и воспользоваться `Reflect`, чтобы корректно привязать `this`. Пол
Более того, вместо того... в первом предложении можно просто оставить "У прокси есть еще одна особенность" ...

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +Проксированный объект невидим для пользователя, но под капотом он позволяет Vue следить за изменениями и уведомлять о них при обращении или редактировании свойств объекта. Начиная с Vue 3, наша реали
наша реализация → реализация

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +Проксированный объект невидим для пользователя, но под капотом он позволяет Vue следить за изменениями и уведомлять о них при обращении или редактировании свойств объекта. Начиная с Vue 3, наша реали
для более удобной работы с такими объектами можно использовать ...

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +Под капотом Vue отслеживает все реактивные объекты, благодаря этому для каждого объекта возвращается свой Proxy.
Кажется висящий пробел в конце

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +Когда требуется доступ к вложенному объекту внутри реактивной Proxy, этот объект _тоже_ конвертируется в Proxy и потом возвращается.
"тоже конвертируется" в курсив

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +При использовании Proxy следует помнить о том, что проксируемый объект не равен оригинальному объекту при строгом сравнении (`===`). Например:
"не равен" тут слитно или раздельно надо писать?

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +Оригинальный и обёрнутый в Proxy объект в большинстве случаев будут вести себя одинаково, но имейте в виду, что они дадут неверный результат в операциях, включающих строгое сравнение, таких как `.fil
в большинстве случаев ведут себя одинаково, но могут выдать неправильный результат в операциях со строгим сравнением

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +Тем не менее, при использовании composition API для явного создания реактивных объектов, лучшей практикой считается никогда не сохранять ссылку на оригинальный объект и работать только с реактивной в
хорошей практикой

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +}) // нет ссылки на оригинал
не ссылается на оригинал

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +У каждого экземпляра компонента есть соответствующий наблюдатель, который вносит в зависимости любые свойства, используемые в момент отрисовки. Позже, при срабатывании сеттера зависимости, он уведоми
уведомит наблюдателя, что приведет к перерисовке компонента

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
>    <common-codepen-snippet title="Second Reactivity with Proxies in Vue 3 Explainer" slug="GRJZddR" tab="result" theme="light" :height="500" :team="false" user="sdras" name="Sarah Drasner" :editable="
Тут title еще бы перевести)

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +Когда объект данных передаётся в экземпляр компонента, Vue превращает его в Proxy. Этот Proxy позволяет Vue следить за изменениями и уведомлять о них при обращении или редактировании свойств объекта.
превращает → конвертирует/преобразует

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +Когда объект данных передаётся в экземпляр компонента, Vue превращает его в Proxy. Этот Proxy позволяет Vue следить за изменениями и уведомлять о них при обращении или редактировании свойств объекта.
С помощью Proxy Vue сможет следить за изменениями и получать уведомления об их изменениях

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +Когда объект данных передаётся в экземпляр компонента, Vue превращает его в Proxy. Этот Proxy позволяет Vue следить за изменениями и уведомлять о них при обращении или редактировании свойств объекта.
Каждое свойство рассматривается как зависимость может?

2021-02-14 08:13 UTC, Alex-Sokolov commented on src/ru/guide/reactivity.md
> +> Если вы используете Vue 2.x или ниже вам могут быть интересны некоторые оговорки для этих версий, о которых можно [подробнее узнать здесь](change-detection.md).
При использовании Vue 2.x или более ранних версий, есть некоторые оговорки, о которых подробнее можно узнать [здесь]

2021-02-14 08:14 UTC, Alex-Sokolov commented
Спасибо за МР! :) несколько моментов добавил, поправите?

2021-02-14 20:31 UTC, Brisstor commented on src/ru/guide/reactivity.md
> +Если обновить первое значение, сумма не скорректируется.
Поменял на 
`Если изменить первое значение, сумма не обновится с его учётом.` чтобы избежать дублирования слова `значения` и обновить - обновится

2021-02-14 20:39 UTC, Brisstor commented on src/ru/guide/reactivity.md
> +При использовании Proxy следует помнить о том, что проксируемый объект не равен оригинальному объекту при строгом сравнении (`===`). Например:
Думаю, раздельно, т.к. здесь он используется как математический термин или просто сравнение.

2021-02-14 20:51 UTC, Brisstor commented on src/ru/guide/reactivity.md
> +Когда объект данных передаётся в экземпляр компонента, Vue превращает его в Proxy. Этот Proxy позволяет Vue следить за изменениями и уведомлять о них при обращении или редактировании свойств объекта.
Тут чуть поправил, на `С помощью Proxy Vue сможет следить за зависимостями и получать уведомления об их изменениях.` Опечатка, видимо :)

2021-02-14 21:01 UTC, Brisstor commented
> Спасибо за МР! :) несколько моментов добавил, поправите?

Да, спасибо, поправил!

2021-02-15 16:32 UTC, Alex-Sokolov approved these changes

2021-02-15 16:32 UTC, merged

2021-02-15 16:33 UTC, Alex-Sokolov commented
Супер! Спасибо :)